# Funding Options for Iluminação LED Niterói

github: danilosfvalim
patreon: danilosfvalim
ko_fi: danilosfvalim
buy_me_a_coffee: danilosfvalim
liberapay: danilosfvalim
issuehunt: danilosfvalim
custom:
  - https://www.paypal.com/donate/?hosted_button_id=YOUR_BUTTON_ID
  - https://opencollective.com/iluminacao-led-niteroi
